### ISSUE TITLE
SSL certificate verify failed 

### ISSUE THREAD

**Issue by Ron4326** [dpursehouse/pygerrit2#109]
When I run pygerrit2, I get an SSL certifcate failed message.

`Error: HTTPSConnectionPool(host='xxxx', port=443): Max retries exceeded with url: /a/changes/?q=status:open%2520owner:self (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
`
For requests, there is an option to set `verify = False`, but I couldn't figure out such an option for pygerrit2.

How do I solve this error ?
Is there an option to set verify as False in pygerrit2 ? If not, should I install a certificate ?

**Comment by dpursehouse** [comment]
You should be able to pass `verify=False` when instantiating the `GerritRestAPI`:

```
  api = GerritRestAPI(verify=False)
```

The `verify` then gets passed in to the requests call.

**Comment by dpursehouse** [comment]
Closing this as resolved.  Please reopen if the above doesn't help.
