### ISSUE TITLE
Bug in review() ? 

### ISSUE THREAD

**Issue by rasjani** [dpursehouse/pygerrit2#132]
Sorry for drive-by issue but:

https://github.com/dpursehouse/pygerrit2/blob/master/pygerrit2/rest/__init__.py#L276

Shouldn't that line be `return self.post(`  ?  At least the docstring says that it will return json object..

**Comment by dpursehouse** [comment]
Yes, I think you're right.  I'll look into it.

**Comment by dpursehouse** [comment]
Thanks for pointing this out.  It's fixed now and will be in the next release which I'll probably do next week.
