### ISSUE TITLE
netrc usage should be enabled by default instead

### ISSUE THREAD

**Issue by ssbarnea** [dpursehouse/pygerrit2#20]
At this moment if user wants to use netrc he has to add extra code and logic. 

Ideally the library should work like this:
* if auth params are specified, use them
* if no auth params are specified try to use netrc ones
* if no .netrc files are loaded fallback to no authentication

**Comment by dpursehouse** [comment]
Sounds reasonable. I don't have time to work on this right now, but I will
review a pull request if you send one.

**Comment by gferon** [comment]
I already have this exact logic somewhere in a script. I can extract it and submit a PR.
