### ISSUE TITLE
pypi formatting is wrong

### ISSUE THREAD

**Issue by oharboe** [dpursehouse/pygerrit2#28]
I don't know if this is the right place to report it, but the pypi HTML page formatting is broken: https://pypi.org/project/pygerrit2/

**Comment by dpursehouse** [comment]
This is a known issue that should be fixed on the master branch, but I
won't know for sure if it works until I make a new release.

**Comment by oharboe** [comment]
thanks!

Den tor. 5. jul. 2018, 12.37 skrev David Pursehouse <
notifications@github.com>:

> This is a known issue that should be fixed on the master branch, but I
> won't know for sure if it works until I make a new release.
>

**Comment by dpursehouse** [comment]
FYI f69aa5ddfe460e6fcce61f1cdfb2929a250c49fe is the commit that should fix it.

I'll leave this issue open until I've done another release and confirmed that it works as expected.

**Comment by oharboe** [comment]
thanks!

Den fre. 6. jul. 2018, 03.55 skrev David Pursehouse <
notifications@github.com>:

**Comment by dpursehouse** [comment]
Released 2.0.7 and the formatting is now fixed.

**Comment by oharboe** [comment]
thanks!

Den tor. 19. jul. 2018, 06.05 skrev David Pursehouse <
notifications@github.com>:
