### ISSUE TITLE
Update the  https://pypi.python.org/pypi/pygerrit2/ version

### ISSUE THREAD

**Issue by choldrim** [dpursehouse/pygerrit2#3]
I use pygerrit2 lib on Python3, there is a problem that has been fixed on  [c3281b4](https://github.com/dpursehouse/pygerrit2/commit/c3281b416df57b6700b27abbe3f91ed1c22a0071), but the pypi version has not be updated yet.

it is an inevitable problem after calling every restAPI successfully, so update is the sooner the better

**Comment by dpursehouse** [comment]
@choldrim yes, I'll make a new release soon.

**Comment by dpursehouse** [comment]
@choldrim 2.0.1 is now available on pypi.  Sorry for the delay.
